### PR TITLE
Maybe add a logo?

### PR DESCRIPTION
**Pull request by ghost**
Just as eye candy a logo could be nice.
I used the green hexagon from the NodeJS logo and the cat from the Yarn logo.

Font used: http://www.fontpalace.com/font-details/MyriadPro-Regular/

### CODE REVIEW

**Comment by ghost** [comment]
It would look like this

unbenannt

**Comment by jonaskello** [comment]
I like it! 👍

**Comment by neciu** [comment]
Cool idea. Please squash it to one commit and I'll merge it!

**Comment by ghost** [comment]
Done.

**Pull request merged**
